### ISSUE TITLE
HashMap Pinning for global maps

### ISSUE THREAD

**Issue by Dunateo** [foniod/redbpf#141]
Hello, 

As I am doing a tc program the creation of the map is not shared between user space and kernel space because we launch it with tc commands such as:

```Bash
tc qdisc add dev lo clsact

sudo tc filter add dev lo ingress \
  bpf da obj target/bpf/programs/limit/limit.elf sec tc_action/limit
```
So in order to share the file descriptor of the map created by this we need to do a global map in order to put it a global namespace so I can get it in other ebpf programs. 

To do that I see that I can modify the 'pinning' in the map options :
 ```
/* This example has a pinning of PIN_OBJECT_NS, so it's private and
 * thus shared among various program sections within the object.
 *
 * A setting of PIN_GLOBAL_NS would place it into a global namespace,
 * so that it can be shared among different object files. A setting
 * of PIN_NONE (= 0) means no sharing, so each tc invocation a new map
 * instance is being created.
 */
```
https://git.kernel.org/pub/scm/network/iproute2/iproute2-next.git/tree/examples/bpf/bpf_shared.c

I saw in the documentation the implementation of Hash table map the High level API for BPF_MAP_TYPE_HASH maps

```Rust
impl<K, V> HashMap<K, V> {
    /// Creates a map with the specified maximum number of elements.
    pub const fn with_max_entries(max_entries: u32) -> Self {
        Self {
            def: bpf_map_def {
                type_: bpf_map_type_BPF_MAP_TYPE_HASH,
                key_size: mem::size_of::<K>() as u32,
                value_size: mem::size_of::<V>() as u32,
                max_entries,
                map_flags: 0,
            },
            _k: PhantomData,
            _v: PhantomData,
        }
    }
```
And in C they have the pinning options :

```C
struct bpf_elf_map {
    u32 type;
    u32 size_key;
    u32 size_value;
    u32 max_elem;
    u32 flags;
    u32 id;
    __u32 pinning;
};

```

Is it possible to choose the pinning value or there is pinning default value ? Can I retrieve the map fd with other solutions for the tc_action program ? 

Thank you

**Comment by rhdxmr** [comment]
RedBPF depends on libbpf. And libbpf offers `int bpf_obj_pin(int fd, const char *pathname);`
The first parameter represents file descriptor of a map and the second parameter is pinning path.
In order to pin the map, create a map first and then pin the map to specific path.

But it seems that RedBPF does not support API for pinning yet.. I guess that you may conduct this by calling `bpf_obj_pin` directly.

**Comment by Dunateo** [comment]
Ok thanks you, so if I understand well, if I do : 
```  bpf_sys::bpf_obj_pin(int fd,  "maps/blocked_packets");```
I should get my file descriptor in /sys/fd/bpf/maps/blocked_packets.

The problem is that didn't find how I can get the file descriptor of my maps in rust.
I create my maps like that from kernel-space: 
```Rust
#[map(link_section = "maps")]
static mut blocked_packets: HashMap<Source, u8> = HashMap::with_max_entries(10240);
```

and the crate bpf_sys depend on std so I have to create a map before with another program and try to attach the map on my tc_action program after the creation ?

**Comment by rhdxmr** [comment]
There are two HashMap structures
- A structure for BPF program is https://github.com/foniod/redbpf/blob/da4d3b893c3d4900e479f35a449c2c06885f4d09/redbpf-probes/src/maps.rs#L28
- A structure for userspace is https://github.com/foniod/redbpf/blob/da4d3b893c3d4900e479f35a449c2c06885f4d09/redbpf/src/lib.rs#L162

HashMap of userspace contains a file descriptor but HashMap of BPF program does not.

But I don't know how to make tc command to use existing pinned maps. And I am not sure it supports that feature.

**Comment by Dunateo** [comment]
Ok I think it's possible to support it but the error may come from another thing. 
I tried to do a strace when I load the program with 
```Bash
sudo strace tc filter add dev lo ingress \
  bpf da obj target/bpf/programs/limit/limit.elf sec tc_action/limit
```
And I found something interesting at the end it does a bpf() syscall for the creation of the map and in this call there is no map_name="" and same for the prog_name=""
```Bash
bpf(BPF_MAP_CREATE, {map_type=BPF_MAP_TYPE_HASH, key_size=8, value_size=1, max_entries=10240, map_flags=0, inner_map_fd=0, map_name="", map_ifindex=0, btf_fd=0, btf_key_type_id=0, btf_value_type_id=0}, 120) = 5

bpf(BPF_PROG_LOAD, {prog_type=BPF_PROG_TYPE_SCHED_CLS, insn_cnt=94, insns=0x559af36d4ad0, license="GPL", log_level=0, log_size=0, log_buf=NULL, kern_version=KERNEL_VERSION(0, 0, 0), prog_flags=0, prog_name="", prog_ifindex=0, expected_attach_type=BPF_CGROUP_INET_INGRESS, prog_btf_fd=0, func_info_rec_size=0, func_info=NULL, func_info_cnt=0, line_info_rec_size=0, line_info=NULL, line_info_cnt=0, attach_btf_id=0, attach_prog_fd=0}, 120) = 6

``` 

When I try to do the same with a Kprobes program the both are filled with the good parameter of my program and I think it comes from that because at the same time it try to create a file for the map in the /sys/fd/bpf/ so a no name file. 

```Rust
#[map(link_section = "maps")]
static mut blocked_packets: HashMap<Source, u8> = HashMap::with_max_entries(10240);
```

Do you think it comes from my own mistake maybe in the map macro or is it specific to redBpf compilation for tc program ?

**Comment by rhdxmr** [comment]
Did you make your target/bpf/programs/limit/limit.elf using redbpf?
Then can you share your code here?

**Comment by Dunateo** [comment]
Hello sorry for the long answer how can I see it ? In the compilation ? 
this is my Cargo.toml
```
[dependencies]
redbpf = { version = "1.3.0", branch = "tc-action", features = ["load"] }
anyhow = "1.0"
# BPF
redbpf-macros = {version = "1.0", branch = "tc-action", optional = true }
redbpf-probes = {version = "1.0", branch = "tc-action", optional = true }
memoffset = { version = "0.5", optional = true }


[features]
default = []
probes = ["redbpf-macros", "redbpf-probes", "memoffset"]

[[bin]]
name = "limit"
path = "src/limit-consumers.rs"
required-features = ["probes"]
```

and my limit programs
```
#![no_std]
#![no_main]
use core::mem::size_of;
use memoffset::offset_of;
use redbpf_macros::map;
use redbpf_probes::tc::prelude::*;

program!(0xFFFFFFFE, "GPL");

#[derive(Clone, Debug)]
#[repr(C)]
struct Source {
  addr: u32,
  port: u32, // should be u16, but need padding (?)
}

#[map(link_section = "maps")]
static mut blocked_packets: HashMap<Source, u8> = HashMap::with_max_entries(10240);



#[tc_action]
fn limit(skb: SkBuff) -> TcActionResult {
  
  //filtering with if 

  Ok(TcAction::Ok)
}

```
It's based on the aquaread Protect The Rabbit project and I used the makefile too with modification of llvm with llvm-11.

I have to add manually at the compilation the redbpf library ? 
Makefile :
```
#Based on Xun Lou Makefile
[env]
DEVICE = "wlp2s0"

[tasks.compile_bpf]
description = "Build BPF program"
install_crate_args = ["cargo-bpf", "--git", "https://github.com/redsift/redbpf.git"]
command = "cargo"
args = ["bpf", "build", "limit"]

[tasks.bpf]
command = "llvm-objcopy-11"
args = [
  "--remove-section",
  ".text", # causes generic trouble in BPF programs
  "--rename-section",
  "maps/blocked_packets=maps", # `tc` only recognize "maps"
  "target/bpf/programs/limit/limit.elf",
]
dependencies = ["compile_bpf"]

[tasks.release]
description = "Build release"
command = "cargo"
args = ["build", "--release"]
dependencies = ["bpf"]

[tasks.dump]
command = "llvm-objdump-11"
args = ["-h", "target/bpf/programs/limit/limit.elf"]

```
Thank you for your time !

**Comment by Dunateo** [comment]
I found a solution to get the file descriptor with bpftool, I can retrieve the id of my map and with the function
```C
bpf_sys::bpf_map_get_fd_by_id(ID_MAP);
```
I retrieve the file descriptor what is complicated is to use this fd with the redbpf crate as there is no function to directly give in parameter of the new hashmap a fd. So I tried to use the C function in libbpf 
```C
redbpf_probes::helpers::gen::bpf_map_update_elem(int fd, void *key, void *value, __u64 flags);
```
but it's not friendly as it's need c_void enum , is there a more easy solution ? Maybe with the bpftool system cmd but it will be a trick and not a proper job
what do you think about it?

**Comment by rhdxmr** [comment]
Hello @Dunateo 
I created a PR in my repo https://github.com/rhdxmr/redbpf/pull/3/files
Check this PR please. This PR is incomplete version for adding map pinning feature but it may help you.

It seems that there are two problems you have.

1. HashMap of redbpf is not suitable for tc. Because redbpf uses bpf_map_def structure but tc uses bpf_elf_map structure. They are different. So I defined new TcHashMap in examples/example-probes/src/tc_test/main.rs
2. current version of redbpf does not support creating Map instance from pinned map. So I added Map::from_pin_path function which can be called in userspace program. And you can monitor the map which is pinned by tc if you use Map::from_pin_path.

The feature for map pinning is currently in progress by myself, and I hope the feature will be added to redbpf soon.

regards,

**Comment by Dunateo** [comment]
Hello @rhdxmr you definitely help me a lot, I was working on trick with bpftool your solution is much better and work very well on userspace and kernelspace. 
The pinned functionality goes to the /sys/fs/bpf/tc/globals and create a persistent map inside which is the default behaviour of Tc map. 

I will send my project when I finish it !
Thank you
