### ISSUE TITLE
Regression: libbpf migration causes 'Operation not permitted' when loading maps

### ISSUE THREAD

**Issue by rsdy** [foniod/redbpf#146]
I have not managed to find why this happens, but I am getting an `Operation not permitted` error when running foniod with the latest `main` branch.

Reverting 1b3c5a60cfa01731fc079ce8a8df61ffd26a1ac8 and c33138d7de322bb92cf2e690af29ebfa0055038f. makes foniod work as expected.

@rhdxmr I will try to get more information about what specifically is failing here, but so far I've been able to localize the error to the `Map::with_map_def` call. If you have run into errors like this, I'd be happy to try any ideas.

**Comment by rsdy** [comment]
I have a hunch we're running into this:
https://github.com/iovisor/bcc/blob/master/src/cc/libbpf.c#L294

I will port this logic and see if that fixes the issue.

**Comment by rhdxmr** [comment]
Quote from Merge tag 'net-next-5.11' of git://git.kernel.org/pub/scm/linux/kernel/git/netdev/net-next
> BPF switch from crude rlimit-based to memcg-based memory accounting

cf) https://lwn.net/Articles/827664/

I am using kernel v5.11 so I could not reproduce rlimit error with my machine.
Ok.. I will test this problem using the older kernel via VM and write some code for fixing it

**Comment by rsdy** [comment]
I think the best approach here is porting the fallback logic from bcc's libbpf. We lost this when we moved away from using that lib as the core.

I tested this on kernel 5.10.
