### ISSUE TITLE
Get size of packet via skbuff variable

### ISSUE THREAD

**Issue by sebastiaoamaro** [foniod/redbpf#182]
Hello everyone,
I was looking into the tc_map_share[1] and tcp_lifetime[2] to find a way to get the size of the packet ( len parameter in the __sk_buff) however I can't seem to access it correctly has someone done this before? It is probably just a line of code similar to accessing a parameter of the ip header, however, I can't seem to crack it.
[1]
https://github.com/foniod/redbpf/blob/main/examples/example-probes/src/tc_map_share/main.rs
[2]
https://github.com/foniod/redbpf/blob/main/examples/example-probes/src/tcp_lifetime/main.rs

Thanks in advance.

**Comment by rhdxmr** [comment]
Hello @sebastiaoamaro 

You can do that like below:
```rust
(*skb.skb).len
```

`skb` is [`redbpf_probes::socket::SkBuff`](https://github.com/foniod/redbpf/blob/412c1a2914008d97699445bf96e95fbced8dcb65/redbpf-probes/src/socket.rs#L41)

And `skb.skb` is `__sk_buff`. It is rust binding of [`__sk_buff`](https://elixir.bootlin.com/linux/latest/source/include/uapi/linux/bpf.h#L5146)

I wish you luck.

**Comment by rhdxmr** [comment]
@sebastiaoamaro 
I just wonder that the answer replied above helped you solve your problem.
If you need more help or have any questions please let me hear from you.
Thanks

**Comment by sebastiaoamaro** [comment]
> @sebastiaoamaro
> I just wonder that the answer replied above helped you solve your problem.
> If you need more help or have any questions please let me hear from you.
> Thanks

Sorry! I forgot to reply it solved it yes, thank you so much!

**Comment by rhdxmr** [comment]
I'm glad to hear that! Thank you 👍 
I'm closing this issue. If you have further questions please feel free to reopen this issue.
