### ISSUE TITLE
error: options `-C embed-bitcode=no` and `-C lto` are incompatible

### ISSUE THREAD

**Issue by rhdxmr** [foniod/redbpf#183]
With rust v1.55, redbpf-tools compilation fails

```
error: options `-C embed-bitcode=no` and `-C lto` are incompatible
```

But with rust v1.54, compilation succeeds

**Comment by rhdxmr** [comment]
Close this issue. it's been resolved by #184

**Comment by p-e-w** [comment]
I suggest making a patch release with the fix, since this bug completely breaks RedBPF for users of the latest Rust version, with no obvious workaround other than downgrading.

**Comment by rhdxmr** [comment]
Thank you @p-e-w for your suggestion. I agree that it is a sufficient rationale to release a new version of redbpf.

@rsdy As p-e-w suggested, why don't we release a new version for users who use rust 1.55?

**Comment by rsdy** [comment]
Thanks both, I have now pressed release on 2.0.2!

**Comment by rsdy** [comment]
Oops, this is actually not going to go through because of an Alpine-specific issue.

**Comment by rhdxmr** [comment]
@rsdy @p-e-w Thanks to you users can get redbpf 2.0.2 from now on.
