### ISSUE TITLE
Corrupted map section in .elf last_map .btf too_small

### ISSUE THREAD

**Issue by sebastiaoamaro** [foniod/redbpf#195]
Hello everyone I am trying to create a kernel space program with these maps,

#[map(link_section = "maps")]
static mut usagePID: TcHashMap<u32, u32> =
    TcHashMap::<u32, u32>::with_max_entries(1024, TcMapPinning::GlobalNamespace);

#[map(link_section = "maps")]
static mut auxPID: TcHashMap<u32, u32> =
    TcHashMap::<u32, u32>::with_max_entries(1024, TcMapPinning::GlobalNamespace);

#[map(link_section = "maps")]
static mut addrPID: PerCpuArray<u32> = PerCpuArray::with_max_entries(10);

#[map(link_section = "maps")]
static mut countPID: PerCpuArray<u32> = PerCpuArray::with_max_entries(10);

however when I compile I get the following libpf error:

libbpf: corrupted maps section in /usr/bin/elffiles/usagemonitor47d84bbf952b6a3b429ee7d5882c4094dbe4b2984a616a56c957f67c37490a5f.elf: last map "_ZN12usagemonitor33_982b3bb7b44241e68c0cea357afc32ae7MAP_BTF17h37b7854cea0b22afE" too small

Does anyone know why this might happen?

Thanks in advance.

**Comment by rhdxmr** [comment]
Hello @sebastiaoamaro 
Sorry for late response.

I guess you opened that `.elf` file using `libbpf` API like `bpf_object__open_file`.
With that assumption I'll explain the point of the problem..

Unfortunately the elf relocatable file that is compiled by redbpf is not designed to support being used by libbpf library :cold_sweat: The elf file has been compiled to be used by redbpf itself.

The error message means that the extra [`btf related structure`](https://github.com/foniod/redbpf/blob/db87c67d1cf5c71b1a8475060cd3110f3424757a/redbpf-macros/src/lib.rs#L270) is too small and it is smaller than `bpf_elf_map` structure.
redbpf currently appends btf related data(the `MapBtf` structure) after the `bpf_map_def` structure.
But this behavior causes error when the `maps` section is read by `libbpf`.

With redbpf it is intended to have only one map in a section. So putting extra data after `bpf_map_def` has not caused problems. But I feel that it might be better to move the extra data into another section to support the case of multi-maps-in-a-section.


And there is another problem with the code you pasted.
`TcHashMap` uses C structure [`bpf_elf_map`](https://github.com/foniod/redbpf/blob/db87c67d1cf5c71b1a8475060cd3110f3424757a/redbpf-probes/src/tc/maps.rs#L32) that is defined by `iproute2` package.
But it is different from [`bpf_map_def`](https://github.com/libbpf/libbpf/blob/e671a47bc279c6a73d1fee5aa522b0979fd1a33a/src/bpf_helpers.h#L130) that is defined by `libbpf`. So you can not use `TcHashMap` with `libbpf` either. They are not interoperable.


----

If you were suffering from the another problem that is different from my assumption, you can correct me.
And if you have suggestions to help redbpf, please share your idea.

regards,

**Comment by sebastiaoamaro** [comment]
I understand, I tried with different sections but it didn't work for the reasons you said. 
I moved on to socket_filters and there I was able to use different maps.
Thanks for the response! Going to close the issue.

**Comment by rhdxmr** [comment]
I'm glad to hear that you found a workaround and solved the problem :+1: 

By this issue, I also got to know that redbpf has not supported multi maps in a section case.
So your question was also meaningful to me. Thank you for the nice question.
And I put a task of enhancing redbpf to support the case into my todo list.
I am going to look into this case after finishing the current task I am working on.

Thanks,
