### ISSUE TITLE
TcHashMap can't set

### ISSUE THREAD

**Issue by Sherlock-Holo** [foniod/redbpf#205]
```rust
#![no_std]
#![no_main]

use core::mem::{size_of, transmute};

use cty::c_void;
use redbpf_macros::map;
use redbpf_probes::tc::prelude::*;

program!(0xFFFFFFFE, "GPL");

#[map(link_section = "redirect_map")]
static mut REDIRECT_MAP: TcHashMap<__be16, u16> =
    TcHashMap::with_max_entries(1024, TcMapPinning::GlobalNamespace);

#[tc_action]
fn test(skb: SkBuff) -> TcActionResult {
    let mut n: __be16 = 1;
    n = n.to_be();

    unsafe {
        REDIRECT_MAP.set(&n, &1);
    }

    Ok(TcAction::Ok)
}
```

when compile this codes and load by tc, it reports

> ```
> Prog section 'tc_action/test' rejected: Permission denied (13)!
>  - Type:         3
>  - Instructions: 12 (0 over limit)
>  - License:      GPL
> 
> Verifier analysis:
> 
> 0: (b7) r1 = 256
> 1: (6b) *(u16 *)(r10 -2) = r1
> 2: (bf) r2 = r10
> 3: (07) r2 += -2
> 4: (18) r1 = 0x0
> 6: (18) r3 = 0x0
> 8: (b7) r4 = 0
> 9: (85) call bpf_map_update_elem#2
> R1 type=inv expected=map_ptr
> processed 8 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0
> 
> Error fetching program/map!
> Unable to load program
> ```

it seems when uses the `bpf_map_update_elem`, the pointer is incorrect? but I don't know what's wrong in 
https://github.com/foniod/redbpf/blob/a9b98c2f9dfa1481a93d46560b0e11deec800865/redbpf-probes/src/tc/maps.rs#L172

**Comment by Sherlock-Holo** [comment]
> ```rust
> #[map(link_section = "maps")]
> ```

even though I change section name to `maps`, it still `r1 = 0 ll`, and tc load report

> ```
> Verifier analysis:
> 
> 0: (b7) r1 = 256
> 1: (6b) *(u16 *)(r10 -4) = r1
> 2: (b7) r1 = 1
> 3: (6b) *(u16 *)(r10 -2) = r1
> 4: (bf) r2 = r10
> 5: (07) r2 += -4
> 6: (bf) r3 = r10
> 7: (07) r3 += -2
> 8: (18) r1 = 0x0
> 10: (b7) r4 = 0
> 11: (85) call bpf_map_update_elem#2
> R1 type=inv expected=map_ptr
> processed 11 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0
> ```

**Comment by rhdxmr** [comment]
@Sherlock-Holo 
I wrote about the LLVM version issue into the tutorial to guide new users what LLVM versions they can choose.
See #217 for more information.
Thank you for your support and patience.

**Comment by Sherlock-Holo** [comment]
This problem still exists... I am using rust 1.58.0-nightly (b416e3892 2021-11-13), cargo-bpf enable llvm13 feature, but it still failed with
> R1 type=inv expected=map_ptr

I even define the bpf_elf_map directly like c codes

```c
struct bpf_elf_map SEC("maps") trackers = {
        .type = BPF_MAP_TYPE_HASH,
        .size_key = sizeof(__u16),
        .size_value = sizeof(__u64),
        .max_elem = 2048,
        .pinning = PIN_GLOBAL_NS,
};
```

```rust
#[allow(non_camel_case_types)]
#[repr(C)]
struct bpf_elf_map {
    type_: u32,
    size_key: u32,
    size_value: u32,
    max_elem: u32,
    flags: u32,
    id: u32,
    pinning: u32,
    inner_id: u32,
    inner_idx: u32,
}

#[no_mangle]
#[link_section = "maps"]
static mut MAP: bpf_elf_map = bpf_elf_map{
    type_: bpf_map_type_BPF_MAP_TYPE_HASH,
    size_key: size_of::<u16>() as _,
    size_value: size_of::<u64>() as _,
    max_elem: 4096,
    flags: 0,
    id: 0,
    pinning: 2,
    inner_id: 0,
    inner_idx: 0
};
```

and try

```rust
unsafe {
    let n = 1u16;
    let v = 2u64;

    bpf_map_update_elem(
        &mut MAP as *mut bpf_elf_map as *mut _,
        &n as *const _ as *const _,
        &v as *const u64 as *const _,
        0,
    );
}
```

failed too...

**Comment by rhdxmr** [comment]
@Sherlock-Holo 
Can you share your project that fails to pass the BPF verifier thru github?

I had installed archlinux in my virtualbox and I have the same environment with you.
I had conducted `pacman -Syu` ;-)
Likewise I use cargo 1.58 nightly.

In my machine, in cloned redbpf source code, this command succeeds:

```console
cargo run --example tc-map-share --no-default-features --features=llvm13 8080
```
But with some modification of the example program

```diff
--- a/examples/example-userspace/examples/tc-map-share.rs
+++ b/examples/example-userspace/examples/tc-map-share.rs
@@ -52,20 +52,18 @@ async fn main() {
     // remove .text section because tc filter does not work if .text exists
     // remove .BTF section because it contains invalid names of BTF types
     // (currently kernel only allows valid symbol names of C)
-    for sec in &[".BTF.ext", ".eh_frame", ".text", ".BTF"] {
-        if !Command::new("llvm-strip-12")
-            .arg("--no-strip-all")
-            .arg("--remove-section")
-            .arg(sec)
-            .arg(&bpf_elf)
-            .status()
-            .expect("error on running command llvm-strip-12")
-            .success()
-        {
-            error!("error on removing section `{}' using llvm-strip-12", sec);
-            return;
-        }
+    if !Command::new("llvm-strip")
+        .arg("--no-strip-all")
+        .args("--remove-section .eh_frame --remove-section .BTF --remove-section .BTF.ext --remove-section .debug_loc --remove-section .debug_info --remove-section .debug_ranges --remove-section .debug_pubnames --remove-section .debug_pubtypes --remove-section .debug_frame --remove-section .debug_line --remove-section .text".split(' '))
+        .arg(&bpf_elf)
+        .status()
+        .expect("error on running command llvm-strip")
+        .success()
+    {
+        error!("error llvm-strip");
+        return;
     }
+
     let new_clsact = Command::new("tc")
         .args("qdisc add dev lo clsact".split(" "))
         .status()
```

**Comment by Sherlock-Holo** [comment]
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2342b8c2ee2f84f00b009644c17ab91d

compile it with cargo-bpf 2.2 with llvm13, when load it by `tc`, reports

> 8 bytes struct bpf_elf_map fixup performed due to size mismatch!
> Map 'NAT_MAP' loaded as pinned!
> ELF contains non-{map,call} related relo data in entry 2 pointing to section 2! Compiler bug?!
> Error fetching program/map!
> Unable to load program

the section of elf file is

> There are 9 section headers, starting at offset 0x3f0:
> 
> 节头：
>   [号] 名称              类型             地址              偏移量
>        大小              全体大小          旗标   链接   信息   对齐
>   [ 0]                   NULL             0000000000000000  00000000
>        0000000000000000  0000000000000000           0     0     0
>   [ 1] tc_action/ingress PROGBITS         0000000000000000  00000040
>        0000000000000208  0000000000000000  AX       0     0     8
>   [ 2] .rodata.cst8      PROGBITS         0000000000000000  00000248
>        0000000000000008  0000000000000008  AM       0     0     8
>   [ 3] license           PROGBITS         0000000000000000  00000250
>        0000000000000004  0000000000000000   A       0     0     1
>   [ 4] version           PROGBITS         0000000000000000  00000254
>        0000000000000004  0000000000000000   A       0     0     4
>   [ 5] maps              PROGBITS         0000000000000000  00000258
>        000000000000001c  0000000000000000  WA       0     0     4
>   [ 6] .symtab           SYMTAB           0000000000000000  00000278
>        00000000000000d8  0000000000000018           8     5     8
>   [ 7] .reltc_actio[...] REL              0000000000000000  00000350
>        0000000000000030  0000000000000010           6     1     8
>   [ 8] .strtab           STRTAB           0000000000000000  00000380
>        0000000000000070  0000000000000000           0     0     1
> Key to Flags:
>   W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
>   L (link order), O (extra OS processing required), G (group), T (TLS),
>   C (compressed), x (unknown), o (OS specific), E (exclude),
>   p (processor specific)

it says `section 2` so I try to remove the section 2 by `llvm-strip --no-strip-all --remove-section .rodata.cst8 ingress.elf`, then load again, it reports

> 8 bytes struct bpf_elf_map fixup performed due to size mismatch!
> Map 'NAT_MAP' loaded as pinned!
> ELF contains non-{map,call} related relo data in entry 2 pointing to section 1! Compiler bug?!
> Error fetching program/map!
> Unable to load program

the section now is 

> There are 8 section headers, starting at offset 0x3c8:
> 
> 节头：
>   [号] 名称              类型             地址              偏移量
>        大小              全体大小          旗标   链接   信息   对齐
>   [ 0]                   NULL             0000000000000000  00000000
>        0000000000000000  0000000000000000           0     0     0
>   [ 1] tc_action/ingress PROGBITS         0000000000000000  00000040
>        0000000000000208  0000000000000000  AX       0     0     8
>   [ 2] license           PROGBITS         0000000000000000  00000248
>        0000000000000004  0000000000000000   A       0     0     1
>   [ 3] version           PROGBITS         0000000000000000  0000024c
>        0000000000000004  0000000000000000   A       0     0     4
>   [ 4] maps              PROGBITS         0000000000000000  00000250
>        000000000000001c  0000000000000000  WA       0     0     4
>   [ 5] .symtab           SYMTAB           0000000000000000  00000270
>        00000000000000c0  0000000000000018           7     4     8
>   [ 6] .reltc_actio[...] REL              0000000000000000  00000330
>        0000000000000030  0000000000000010           5     1     8
>   [ 7] .strtab           STRTAB           0000000000000000  00000360
>        0000000000000063  0000000000000000           0     0     1
> Key to Flags:
>   W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
>   L (link order), O (extra OS processing required), G (group), T (TLS),
>   C (compressed), x (unknown), o (OS specific), E (exclude),
>   p (processor specific)

I don't think I can remove the `tc_action/ingress`...

**Comment by Sherlock-Holo** [comment]
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=31ec28ddc0855cf6432ec6df804d3012

if I handle the bpf_elf_map on my own, it can be loaded by tc directly

**Comment by rhdxmr** [comment]
@Sherlock-Holo 

In the first code you posted
> https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2342b8c2ee2f84f00b009644c17ab91d

It seems that this code line causes problem.

```rust
NAT_MAP.set(&source_port, &1);
```

`&1` creates a reference of read only data that is stored at `.rodata.cst8` section.

**Comment by Sherlock-Holo** [comment]
oh yes, the `&1` cause this problem, in rust this is a normal case, maybe in bpf it is not allowed

**Comment by rhdxmr** [comment]
I am closing this issue.
Thanks to this issue I could enhance RedBPF.
Thank you for filing this issue and for letting me know of your problems that may be helpful to other users.
