### ISSUE TITLE
ERROR loading BPF program with a verifier message "invalid func unknown#114"

### ISSUE THREAD

**Issue by d0u9** [foniod/redbpf#212]
I am trying to follow this [tutorial](https://github.com/foniod/redbpf/blob/main/TUTORIAL.md), and failed due to this error.

![image](https://user-images.githubusercontent.com/7038479/140298759-4a884b7f-2aab-42f5-a042-46406df6a37c.png)

As a newbie to eBPF. It is really hard to figure out what is going on.

**Comment by rhdxmr** [comment]
Hello @d0u9 

BPF helper function number 114 is `bpf_probe_read_user_str`. It was first shown at kernel v5.5.

If your kernel is older than v5.5 you can call the function. But you can call old version `bpf_probe_read_str` instead.

**Comment by rhdxmr** [comment]
BPF subsystem in the Linux kernel is still in development rapidly. So if you don't mind, I recommend you to use recent version of kernel if you are interested in BPF. It would be better experience. But of course, it is not a must-do.

**Comment by d0u9** [comment]
Hi, @rhdxmr.

Thanks very much for your quick reply.

Does the first error, `error on bpf_load_btf: magic: 0xeb9f`, not matter?

**Comment by rhdxmr** [comment]
@d0u9 
The first error message means error loading BTF to kernel. Message starting from "magic ..." is written by BPF verifier of kernel.
But loading BTF is optional procedure so that failure of the procedure does not affect the whole process.

**Comment by rhdxmr** [comment]
And.. I am not sure why loading BTF failed.

The verifier log says the btf type whose id is 6 is illegal.. But I don't have idea why the BTF info is corrupted. It is generated by LLVM and redbpf corrects it a little bit. But I have not experienced this symtom..

**Comment by d0u9** [comment]
Ok, I get it. Thanks for your kind help.

**Comment by rhdxmr** [comment]
@d0u9 
I wrote about this problem into the tutorial to help new users not struggle with this problem again.
See #217 for more information.
Thanks.
