### ISSUE TITLE
Parse Error Map

### ISSUE THREAD

**Issue by sebastiaoamaro** [foniod/redbpf#214]
Hello again, when using the most recent eBPF repository I started to get a Parse Error Map when loading the program code.
let mut loaded = Loader::load(probe_code()).expect("error loading BPF program");
This, however, does not happen when using an older version, I also noticed that there were some commits related to Maps recently.
Code related to the part of the maps here:
```
#![no_std]
#![no_main]
use core::mem::{self, MaybeUninit};
use memoffset::offset_of;

use redbpf_probes::socket_filter::prelude::*;

use monitor::usage::{SocketAddr,message};

#[map(link_section = "maps/perf_events")]
static mut perf_events: PerfMap<message> = PerfMap::with_max_entries(1024);
#[map(link_section = "maps/usage")]
static mut usage: HashMap<u32, u32> = HashMap::with_max_entries(4096);

#[map(link_section = "maps/time")]
static mut time: HashMap<u32, u64> = HashMap::with_max_entries(4096);
´´´
Thanks in advance.

**Comment by rhdxmr** [comment]
@sebastiaoamaro 
The code you pasted here looks normal.
Did you clean the target and build it again?

```console
$ cargo clean
$ cargo build
```

If the same error happens again, can you debug with `rust-gdb` and share a specific point where the error occurs?

**Comment by sebastiaoamaro** [comment]
I am working with containers and can't run rust-gdb inside them. Will create a simple program and post what I got later.
Thanks for the response!

**Comment by sebastiaoamaro** [comment]
I ran this program:
```
use redbpf::load::Loader;
#[tokio::main(flavor = "current_thread")]
async fn main() {
    let iface = "eth0";
    let mut raw_fds = Vec::new();
    let mut loaded = Loader::load(probe_code()).expect("error loading BPF program");

    //insert socket filter
    for sf in loaded.socket_filters_mut() {
        if let Ok(sock_raw_fd) = sf.attach_socket_filter(iface) {
            raw_fds.push(sock_raw_fd);
        }
    }
}
```
And got this:
thread 'main' panicked at 'error loading BPF program: ParseError(Map)', src/main.rs:6:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Inferior 1 (process 12729) exited with code 0145]
In rust-gdb, not an expert at using rust-gdb, but after looking into the load function in https://github.com/foniod/redbpf/blob/main/redbpf/src/btf.rs the only meaningful fuction "load" runs is bpf_load_btf, which is implemented in https://github.com/libbpf/libbpf/blob/6e6f18ac5d811706b6fa5416c07b22f22d972b32/src/btf.c and is probably? the one giving the error.
 
Since the libbpf didn't change I would say it might be a problem in RedBPF somewhere.

**Comment by rhdxmr** [comment]
@sebastiaoamaro 
Could you do me a favor? Can you add some code to your sample program for enabling debug messages and post the message here?
You can enable the message as follows: [enabling debug]( https://github.com/foniod/redbpf/blob/cc407bf04298263653cf5b98677bcf0a84bb633e/examples/example-userspace/examples/hashmaps.rs#L17-L20)

**Comment by sebastiaoamaro** [comment]
Debug gave this:

```
Nov 15 19:20:59.119 ERROR redbpf: 3 maps are defined in section `maps/usage`. Only `maps` section is allowed to accommodate multiple maps
thread 'main' panicked at 'error loading BPF program: ParseError(Map)', src/main.rs:20:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I changed the section to "maps" instead of "maps/**" and solved it. I think multiple examples in the userspace probes have maps defined like this, might be something worth to look at.

**Comment by rhdxmr** [comment]
@sebastiaoamaro 

> Nov 15 19:20:59.119 ERROR redbpf: 3 maps are defined in section `maps/usage`. Only `maps` section is allowed to accommodate multiple maps

This message says, 3 different maps are defined in `maps/usage` section.
For example,
```rust
#[map(link_section = "maps/usage")]
static mut usage: HashMap<u32, u32> = ...;

#map(link_section = "maps/usage")]
static mut usage2: HashMap<u32, u32> = ...;

#map(link_section = "maps/usage")]
static mut usage3: HashMap<u32, u32> = ...;
```
It is not allowed by redbpf... redbpf just parses only 1 map definition from one map section.
And the name of the map is extracted from the section name.
If section name is `maps/usage` then `usage` is the name of the map.
If section name is `maps/usage2` then `usage2` is the name of the map.

It is okay to have multiple maps that are defined in different sections.
For example,
```rust
#[map(link_section = "maps/usage")]
static mut usage: HashMap<u32, u32> = ...;

#map(link_section = "maps/usage2")]
static mut usage2: HashMap<u32, u32> = ...;

#map(link_section = "maps/usage3")]
static mut usage3: HashMap<u32, u32> = ...;

```

**Comment by rhdxmr** [comment]
@sebastiaoamaro 
I just realized that users who didn't enable `tracing` for showing debug message can't see any useful message from redbpf. Oh no... there should be a solution for this situation.

If you have any suggestion about the behavior of parsing maps, please share your thought with maintainers of redbpf.
Thanks,

**Comment by sebastiaoamaro** [comment]
Ok, I will close the issue since the problem is solved.
