### ISSUE TITLE
When I run the xdp example, I report an error : libbpf: Kernel error message: virtio_net: Too few free TX rings available

### ISSUE THREAD

**Issue by nandy007** [foniod/redbpf#238]
My example runs in the Ubuntu virtual machine， and compile is ok.

I search from google ，get an answer ： Number of queues on the tap device needs to be 2 * Nvcpu。

But，I donot know how to set。

**Comment by rsdy** [comment]
I think you should try something like `ethtool -L eth1 rx N tx N` before tring your code again, where `N` is 2*Nvcpu, eg. `2` if you have 1 core allocated to the VM: `ethtool -L eth1 rx 2 tx 2`

**Comment by kevi-sun** [comment]
can you share your code, when loading XDP prog, it need the interface name (which you can get from "IP address") and load mode (that is defined in xdp::Flags)
