### ISSUE TITLE
README.md: broken links

### ISSUE THREAD

**Issue by mehrdadrad** [foniod/redbpf#240]
I just noticed the below links have been broken (404) at the main readme.

https://foniod.org/api/redbpf/
https://foniod.org/api/redbpf_probes/
https://foniod.org/api/redbpf_macros/
https://foniod.org/api/cargo_bpf/

**Comment by rhdxmr** [comment]
@mehrdadrad 

You can find the documentation here now

https://docs.rs/redbpf/latest/redbpf/
https://docs.rs/redbpf-probes/latest/redbpf_probes/
https://docs.rs/redbpf-macros/latest/redbpf_macros/

Thanks for letting me know of this. I'll fix the README soon.

**Comment by rhdxmr** [comment]
@mehrdadrad 
This issue is handled by #243 
Thank you.
