### ISSUE TITLE
Preparing new release

### ISSUE THREAD

**Issue by rhdxmr** [foniod/redbpf#252]
It has been 51 days since we released the last version.

And there exist several improvements after v2.2.0 like inspecting get/get_mut
call at compile-time, supporting aarch64, adding devmap, support BTF for tc,
bumping up bindgen and so on.

So IMO it's good time to release v2.3.0.

@rsdy
How do you think about it?

If you say yes then I'll prepare a release note.

**Comment by rhdxmr** [comment]
cc @bobrik

**Comment by rhdxmr** [comment]
- #245

**Comment by rsdy** [comment]
Would be a good opportunity to act on #248 as well, what do you think?

**Comment by rhdxmr** [comment]
I hope to solve #248 too but I am inclined to do it at next opportunity (next release).
Because solving #248 would be a breaking change so I think it needs enough time to do it correctly before releasing new version.

How about collecting some more breaking changes before bump up the major version?
For example, #247 raised a question but I couldn't find best answer.

**Comment by rsdy** [comment]
Ok, I like this approach. Let's cut a last release for 2.x, and then we can move to 3.x major.

**Comment by rhdxmr** [comment]
RedBPF v2.3.0 had been released yesterday.
Thanks,
