### ISSUE TITLE
LLVM_SYS_130_PREFIX= $HOME /llvm-13-release/ cargo install cargo-bpf fail

### ISSUE THREAD

**Issue by jaciot** [foniod/redbpf#265]
No suitable version of LLVM was found system-wide or pointed
              to by LLVM_SYS_120_PREFIX.
       
              Consider using `llvmenv` to compile an appropriate copy of LLVM, and
              refer to the llvm-sys documentation for more information.
       
              llvm-sys: https://crates.io/crates/llvm-sys
              llvmenv: https://crates.io/crates/llvmenv
   --> /root/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/llvm-sys-120.2.2/src/lib.rs:486:1
    |
486 | / std::compile_error!(concat!(
487 | |     "No suitable version of LLVM was found system-wide or pointed
488 | |        to by LLVM_SYS_",
489 | |     env!("CARGO_PKG_VERSION_MAJOR"),
...   |
496 | |        llvmenv: https://crates.io/crates/llvmenv"
497 | | ));
    | |__^

rustc version:1.58.0
os version:Centos 7
kernel:Linux 5.16.1-1.el7.elrepo.x86_64

I have no in-depth understanding of LLVM. If you are free, could you please tell me how to solve this problem？

**Comment by jaciot** [comment]
it has been solved!

**Comment by wm775825** [comment]
you need to specify the version of llvm

LLVM_SYS_130_PREFIX=<path>  cargo install  cargo-bpf --no-default-features --features=llvm13,command-line.

because default version of llvm used by llvm-sys is 12, so the error info is "LLVM_SYS_120_PREFIX" rather than "LLVM_SYS_130_PREFIX"。
