### ISSUE TITLE
Tutorial kprobe on `do_sys_open` records no events

### ISSUE THREAD

**Issue by joachimneu** [foniod/redbpf#277]
I walked through the [basic tutorial](https://github.com/foniod/redbpf/blob/0f251d03b43bb301b501b38e37cb0804913f2554/TUTORIAL.md) without error, but did not get any output/events. Progs and maps as inspected with `bpftool` seemed fine. Eventually I realized that even [this kprobe usage example](https://www.infradead.org/~mchehab/rst_conversion/trace/kprobetrace.html#usage-examples) doesn't record any events, suggesting the problem is outside the scope of `redbpf`. Then tried the `echo` example and it works.

I don't know where this belongs / what causes it / how to fix it. I thought I post it here to make folks aware and help those who end up google'ing for the same "error".

Kernel: `5.16.5-arch1-1`
LLVM: `13.0.0-6`

**Comment by cr0ax** [comment]
Same problem

`5.15.16-1-MANJARO`
`13.0.0`

**Comment by cr0ax** [comment]
I think I got it:
https://man.archlinux.org/man/kernel_lockdown.7
Don't know how to fix it just yet, other then disabling secure boot.
Will test it out tomorrow

**Comment by cr0ax** [comment]
Ok so I couldn't sleep...

```
sudo bpftrace -e 'tracepoint:syscalls:sys_enter_open { printf("%s %s\n", comm, str(args->filename)); } '
```
Just seems to do nothing, but on the other hand

```
sudo bpftrace -e 'tracepoint:syscalls:sys_enter_openat { printf("%s %s\n", comm, str(args->filename)); }'
```
does give output.

It turns out the issue was not kernel lockdown, but instead the same referenced in [this thread](https://gitanswer.com/bpftrace-no-output-from-sys-enter-open-c-606447456)

> For those stumbling about this issues like me, the problem is that most processes don't use the open syscall, but the openat syscall instead.

But for some reason I can't get the tutorial to attach to anything else...

**Comment by cr0ax** [comment]
Alright, check out https://github.com/foniod/redbpf/issues/266

The tutorial was changed from `do_sys_openat2`, which actually works for me.

I will probably open a PR tomorrow to add some kind of advisory to the tutorial.

And you know what? I learned something about my system using bpf ;)

**Comment by rhdxmr** [comment]
Hello @joachimneu 
Does the answer from @cr0ax solve your issue?

**Comment by joachimneu** [comment]
Haven't tried, but makes sense, thanks!
