### ISSUE TITLE
Observing multiple functions

### ISSUE THREAD

**Issue by toasthorse** [foniod/redbpf#279]
Hello,

from what I understood from the tutorial and from my own kprobe program observing a kernel function, each program needs its own buffer (e.g. PerfMap) to forward events to the userspace program. Is this correct or is there a possibility to observe two kernel functions and store their events in the same buffer so that a single thread in the userspace program can process events from both functions?

Thanks!

**Comment by rhdxmr** [comment]
Good question.

I have not written two BPF programs that share one perf event buffer.
But I guess it is possible to make two kprobe BPF programs that share one perf event buffer.

However, although I can write it, I'd rather not do that.
Because doing that makes two different kinds of data be mixed.
In userspace program, it is complicated to distinguish between two types.
Of course, it is possible to distinguish but it seems not easier than using separate perf event buffers.

This is merely my theory that does not have proof.

**Comment by toasthorse** [comment]
Thank you for your answer. In my case, the two types of data are actually the same, therefore I want them to be mixed in a single buffer I can process them the same way. Specifically, the kernel functions are `__dev_queue_xmit` and `__dev_direct_xmit` through which socket buffers pass, containing data which was sent from a socket. A packet can only pass through one of them but not both; `__dev_direct_xmit` is used for packets which bypass the qdisc layer in the kernel. The goal would be to capture traffic from any type of socket, also those which have the option set to bypass the qdisc layer. Can i declare a "global" PerfMap for both kprobes?

**Comment by rhdxmr** [comment]
```rust
#[map]
static mut PERF: PerfMap<Something> = PerfMap::with_max_entries(10240);


#[kprobe]
fn __dev_queue_xmit(regs: Registers) {
   ...
   PERF.insert(regs.ctx, ...);
}

#[kprobe]
fn __dev_direct_xmit(regs: Registers) {
   ...
   PERF.insert(regs.ctx, ...);
}
```

Does this work for you?

**Comment by toasthorse** [comment]
It somehow didn't occur to me put both functions in the same file, but yes it works! I added both of the function to the loaded program like so:

```Rust
    loaded
        .kprobe_mut("__dev_queue_xmit")
        .expect("error on Loaded::kprobe_mut")
        .attach_kprobe("__dev_queue_xmit", 0)
        .expect("error on KProbe::attach_kprobe");
    loaded
        .kprobe_mut("__dev_direct_xmit")
        .expect("error on Loaded::kprobe_mut")
        .attach_kprobe("__dev_direct_xmit", 0)
        .expect("error on KProbe::attach_kprobe");
```
I tested it with trafgen which by default uses ` __dev_direct_xmit` and it works perfectly. Thank you!
