### ISSUE TITLE
[Question] trying to access the parameter of `kprobe:__x64_sys_chdir`?

### ISSUE THREAD

**Issue by NishantJoshi00** [foniod/redbpf#295]
I was writing a program to register the activity of chdir in my Linux system, after `man chdir`, I found that there is only one argument to the said command, I tried to follow the tutorial for `do_sys_open` closely to replicate the same behavior from my case, but none of the chdir calls are being caught by it. 
ps: I am very new to eBPF still learning how it all works, please point me towards the right direction
Thanks!

**Comment by rhdxmr** [comment]
Hey @NishantJoshi00 

There is also `fchdir` syscall that changes cwd.
You could try attaching that function too.

**Comment by NishantJoshi00** [comment]
Hello @rhdxmr,
Thanks for pointing out, it seems `$ cd` calls `fchdir`
I checked through logs the probes are getting attached perfectly

`int chdir(const char *path);`
```rust
let path = regs.parm1() as *const u8
```
👆 when passed to `bpf_probe_read_user_str` yields a negative value

where as for `fchdir` file descriptor is passed i think for this I need to perform some userspace manipulation by passing the `int` through perfmap

@rhdxmr Thanks for the help!

I am still confused, having no access to std in kernel space is really difficult to work with 🤣

**Comment by NishantJoshi00** [comment]
Thanks! so much @rhdxmr
This was huge help!
